version = 1
product = "beamscale"
mode = "single-host"
listen = "127.0.0.1:8081"
daemon_url = "http://127.0.0.1:9587"

[components.daemon]
repo = "https://github.com/beamscale/beamscale-desktop-daemon.git"
rev = "3a42807da31b772016968776c0ff68a9b15f6da4"
build = ["cargo", "build", "--release"]

[components.runtime]
repo = "https://github.com/beamscale/bmscl-supervisor.git"
rev = "17956df9b0bbde7d0bb8832a842f8e2cf0ebc504"
build = ["rebar3", "compile"]

[components.compiler]
repo = "https://github.com/beamscale/bmscl-compiler.git"
rev = "b539cc31d814d78a0c34604762c5060c9ad27e34"
build = ["cargo", "build", "--release"]

[components.cli]
repo = "https://github.com/beamscale/bmscl-cli.git"
rev = "eb8405939ecd54f3ccf27c18da0c6ef04807030d"
build = ["cargo", "build", "--release"]

[cloudflare]
origin = "http://127.0.0.1:8081"
